[package]
name = "image-roll"
version = "0.1.0"
authors = ["Robert Węcławski <r.weclawski@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.14"
env_logger = "0.8.3"
glib = "0.10.3"
gdk = "0.13.2"
gdk-pixbuf = "0.9.0"
cairo-rs = "0.9.1"
approx = "0.4.0"
anyhow = "1.0"
wallpaper = { git = "https://github.com/Vanille-N/set_wallpaper", default-features = false }

[dependencies.gtk]
version = "0.9.2"
features = ["v3_22_29"]

[dependencies.gio]
version = "0.9.1"
features = ["v2_44"]