[package]
name = "image-roll"
version = "0.1.0"
authors = ["Robert Węcławski <r.weclawski@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glib = "0.10.3"
gdk = "0.13.2"
gdk-pixbuf = "0.9.0"
cairo-rs = "0.9.1"
approx = "0.4.0"

[dependencies.gtk]
version = "0.9.2"
features = ["v3_22"]

[dependencies.gio]
version = "0.9.1"
features = ["v2_44"]

[package.metadata.deb]
license-file = ["LICENSE", "0"]
section = "graphics"
assets = [
    ["target/release/image-roll", "opt/image-roll/", "755"],
    ["README.md", "usr/share/doc/image-roll/README", "644"],
    ["src/resources/image-roll.desktop", "usr/share/applications/", "644"],
    ["src/resources/com.github.weclaw1.ImageRoll.svg", "usr/share/icons/hicolor/scalable/apps/", "644"],
    ["src/resources/com.github.weclaw1.ImageRoll.Devel.svg", "usr/share/icons/hicolor/scalable/apps/", "644"],
    ["src/resources/com.github.weclaw1.ImageRoll-symbolic.svg", "usr/share/icons/hicolor/scalable/apps/", "644"],
]
